sudo: required
language: php
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

php:
  - 7.1

services:
  - mysql

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  - travis_retry composer install --no-interaction

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - cp .travis.env .env
  - php artisan serve &
  - php artisan key:generate

script:
  - php artisan dusk