sudo: required
language: php
dist: trusty

php:
  - 7.1

node_js:
  - 6.9.5

install:
  - travis_retry composer install --no-interaction
  - travis_retry yarn install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - php artisan serve &

script:
  - php artisan dusk